export const alarmsData = [
  {
    id: '1',
    label: 'En 8 horas',
    time: '07:00',
    period: 'AM',
    name: 'Rutina matutina',
    challenge: 'Reto de sentadillas',
    challengeIcon: 'dumbbell',
    enabled: true,
    dots: 6,
    days: [true, true, true, true, true, false, false],
    sound: 'Canto de aves',
    vibration: 'Pulsos',
    desafio: 'Cognitivo',
    obligatorio: true,
    snoozeMax: 5,
  },
  {
    id: '2',
    label: 'Mañana',
    time: '09:00',
    period: 'AM',
    name: 'Alarma de respaldo',
    challenge: 'Agitar para apagar',
    challengeIcon: 'cellphone',
    enabled: true,
    dots: 0,
    days: [true, true, true, true, true, false, false],
    sound: 'Timbre',
    vibration: 'Contante',
    desafio: 'Cognitivo',
    obligatorio: true,
    snoozeMax: 5,
  },
];
